In [1]:

import pandas as pd
import numpy as np

In [2]:
import kagglehub

path = kagglehub.dataset_download("arashnic/book-recommendation-dataset")

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.11), please consider upgrading to the latest version (0.3.12).

In [3]:
print(path)

C:\Users\anupa\.cache\kagglehub\datasets\arashnic\book-recommendation-dataset\versions\3

In [3]:

books=pd.read_csv(path+"\Books.csv")

<>:1: SyntaxWarning: invalid escape sequence '\B'
<>:1: SyntaxWarning: invalid escape sequence '\B'
C:\Users\anupa\AppData\Local\Temp\ipykernel_15868\122461441.py:1: SyntaxWarning: invalid escape sequence '\B'
  books=pd.read_csv(path+"\Books.csv")
C:\Users\anupa\AppData\Local\Temp\ipykernel_15868\122461441.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books=pd.read_csv(path+"\Books.csv")

In [ ]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [5]:

books.drop(['Image-URL-S','Image-URL-M','Image-URL-L'],axis=1,inplace=True)

In [6]:

books.head(2)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada

In [7]:
users=pd.read_csv(path + "/Users.csv")

In [8]:

users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [9]:

users.rename(columns={'User-ID':'user_id','Location':'location','Age':'age'}, inplace=True)

In [10]:

users.tail(2)

        user_id                   location  age
278856   278857  knoxville, tennessee, usa  NaN
278857   278858       dublin, n/a, ireland  NaN

In [11]:

users['age'].isna().sum()

110762

In [12]:
users['age'].fillna(0, inplace=True)

C:\Users\anupa\AppData\Local\Temp\ipykernel_15868\2313837677.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  users['age'].fillna(0, inplace=True)

In [13]:
ratings=pd.read_csv(path + "/Ratings.csv")

In [14]:

ratings.tail(3)

         User-ID         ISBN  Book-Rating
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

In [15]:

ratings.rename(columns={'User-ID':'user_id','Book-Rating':'rating'}, inplace=True)

In [16]:
ratings.shape

(1149780, 3)

In [17]:
books.shape

(271360, 5)

In [18]:
users.shape

(278858, 3)

In [19]:

ratings['user_id'].value_counts().shape

(105283,)

Now we should consider user we have read 150+ books. Yesle garda hamle books ko knowledge bhayeko manxe haru ko basis ma aru lai recommend garxau

In [20]:
desired_users=ratings['user_id'].value_counts()>150
desired_users
desired_users=desired_users[desired_users]

In [21]:
x=desired_users.index

Now we wil need to consider ratings of those who have read such amount of books

In [22]:
ratings=ratings[ratings['user_id'].isin(x)]
ratings.shape

(582644, 3)

In [23]:
ratings

         user_id        ISBN  rating
1456      277427  002542730X      10
1457      277427  0026217457       0
1458      277427  003008685X       8
1459      277427  0030615321       0
1460      277427  0060002050       0
...          ...         ...     ...
1149633   276680  1884910033       0
1149634   276680  1888173408       7
1149635   276680  1888173564       8
1149636   276680  1888173572       0
1149637   276680  1931561648       9

[582644 rows x 3 columns]

Lets merge these two..if isbn of both is same they will stay else not..here isbn is not a unique id..it is inner join by default

In [24]:
ratings_plus_book=ratings.merge(books,on='ISBN')

In [25]:
ratings_plus_book.head(2)

,user_id,ISBN,rating,Book-Title,Book-Author,Year-Of-Publication,Publisher
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons

Now lets consider the books which are rated by 75+ users

In [26]:
rating_count = ratings_plus_book.groupby('Book-Title')['rating'].count().reset_index()

In [27]:

rating_count

                                               Book-Title  rating
0        A Light in the Storm: The Civil War Diary of ...       3
1                                   Always Have Popsicles       1
2                    Apple Magic (The Collector's series)       1
3        Beyond IBM: Leadership Marketing and Finance ...       1
4        Clifford Visita El Hospital (Clifford El Gran...       1
...                                                   ...     ...
170106  Ã?Â?ber die Pflicht zum Ungehorsam gegen den S...       3
170107                                      Ã?Â?lpiraten.       1
170108                     Ã?Â?rger mit Produkt X. Roman.       2
170109                              Ã?Â?stlich der Berge.       1
170110                                  Ã?Â?thique en toc       1

[170111 rows x 2 columns]

In [28]:

rating_count.rename(columns={'rating':'number_of_ratings'}, inplace=True)

In [29]:

ratings_plus_book=ratings_plus_book.merge(rating_count, on='Book-Title')

In [30]:

ratings_plus_book.head(2)

,user_id,ISBN,rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,number_of_ratings
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,88
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,7

In [31]:
ratings_plus_book.shape

(539227, 8)

In [32]:
ratings_plus_book=ratings_plus_book[ratings_plus_book['number_of_ratings']>75]

In [33]:

ratings_plus_book.shape

(49264, 8)

In [34]:
ratings_plus_book.rename(columns={'Book-Title':'title','Book-Author':'author','Year-Of-Publication':'year','Publisher':'publisher','number_of_ratings':'number_of_ratings'}, inplace=True)

In [35]:

ratings_plus_book.head(2)

,user_id,ISBN,rating,title,author,year,publisher,number_of_ratings
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,88
13,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,155

In [36]:
ratings_plus_book.drop_duplicates(['user_id','title'], inplace=True)

In [37]:

ratings_plus_book.shape

(47698, 8)

Item Based Collaborative Filtering

In [38]:
book_pivotib=ratings_plus_book.pivot_table(columns='user_id',index='title',values='rating')

In [39]:

book_pivotib

user_id,254,1733,1903,2033,2110,2276,2766,2891,2977,3363,...,274308,274808,275970,276018,276680,277427,277478,277639,278188,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Bend in the Road,0.0,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Winter Solstice,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
Wish You Well,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Without Remorse,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Wuthering Heights,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
book_pivotib.fillna(0,inplace=True)
book_pivotib.head(2)

user_id,254,1733,1903,2033,2110,2276,2766,2891,2977,3363,...,274308,274808,275970,276018,276680,277427,277478,277639,278188,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Yeha there are multiple zeros, we dont want those..

In [41]:
from scipy.sparse import csr_matrix
sparse_ib=csr_matrix(book_pivotib)

In [42]:

type(sparse_ib)

scipy.sparse._csr.csr_matrix

In [43]:
from sklearn.neighbors import NearestNeighbors
modelib=NearestNeighbors(metric='minkowski',p=2,algorithm='brute')

In [44]:
modelib.fit(sparse_ib)

NearestNeighbors(algorithm='brute')

In [45]:
distances,suggestions=modelib.kneighbors(book_pivotib.iloc[132,:].values.reshape(1,-1),n_neighbors=6)

c:\Users\anupa\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[WinError 2] The system cannot find the file specified
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "c:\Users\anupa\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "c:\Users\anupa\anaconda3\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\anupa\anaconda3\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\Users\anupa\anaconda3\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

In [46]:
distances

array([[ 0.        , 69.49100661, 70.9365914 , 71.05631569, 71.49125821,
        71.52621897]])

In [47]:
suggestions

array([[132, 165, 279, 362,   3, 412]], dtype=int64)

In [48]:

book_pivotib.index[132]

"Harry Potter and the Sorcerer's Stone (Book 1)"

In [49]:

x=np.array(suggestions)
y=x.flatten()

In [50]:

for i in y:
    print(book_pivotib.index[i])

Harry Potter and the Sorcerer's Stone (Book 1)
Journey
The Burden of Proof
The Sum of All Fears (Jack Ryan Novels)
4 Blondes
Winter Solstice

In [51]:
def recommend_book_itemBased_CF(book_name):
    book_id = np.where(book_pivotib.index == book_name)[0][0]
    distance, suggestions = modelib.kneighbors(book_pivotib.iloc[book_id, :].values.reshape(1, -1), n_neighbors=6)
    for i in suggestions.flatten():
        print(book_pivotib.index[i])

In [52]:
recommend_book_itemBased_CF('Wicked: The Life and Times of the Wicked Witch of the West')

Wicked: The Life and Times of the Wicked Witch of the West
Journey
The Weight of Water : A Novel Tag: Author of Resistance and Strange Fits of Passion
A Virtuous Woman (Oprah's Book Club (Paperback))
4 Blondes
The Angel of Darkness

In [63]:
import joblib
joblib.dump(modelib, 'model.pkl')

['model.pkl']

User Based Collaborative Filtering

In [53]:
book_pivotub=ratings_plus_book.pivot_table(columns='title', index='user_id', values='rating')

In [54]:

book_pivotub.fillna(0, inplace=True)

In [55]:

book_pivotub

title,1984,1st to Die: A Novel,2nd Chance,4 Blondes,A Bend in the Road,A Case of Need,"A Child Called \It\"": One Child's Courage to Survive""",A Heartbreaking Work of Staggering Genius,A Is for Alibi (Kinsey Millhone Mysteries (Paperback)),A Map of the World,...,Whispers,White Oleander : A Novel,White Oleander : A Novel (Oprah's Book Club),Wicked: The Life and Times of the Wicked Witch of the West,Wild Animus,Winter Solstice,Wish You Well,Without Remorse,Wuthering Heights,"\O\"" Is for Outlaw"""
user_id,,,,,,,,,,,,,,,,,,,,,
254,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1733,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1903,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2033,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2110,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277427,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
277478,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
277639,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278188,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
278418,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [56]:

from scipy.sparse import csr_matrix
sparse_ub=csr_matrix(book_pivotub)

In [57]:
from sklearn.neighbors import NearestNeighbors
modelub=NearestNeighbors(algorithm='brute',metric='minkowski',p=2)

In [58]:

modelub.fit(sparse_ub)

NearestNeighbors(algorithm='brute')

In [59]:
def book_recommendations_UserBased_CF(user_id):
    import random
    
    try:
        serial_no=book_pivotub.index.get_loc(user_id)
        #serial_no=np.where(book_pivotub.index==user_id)[0][0]
    except KeyError:
        print("Sorry! UserID",user_id,"not Valid.")
        
    distance,suggestions=modelub.kneighbors(book_pivotub.loc[user_id].values.reshape(1,-1), n_neighbors=6)
    # we could also use distance,suggestions=modelub.kneighbors(book_pivotub.iloc[serial_no].values.reshape(1,-1), n_neighbors=6)
    h=[]
    for i in suggestions:
        h.append(book_pivotub.index[i])
    y=[h[0][1],h[0][2],h[0][3],h[0][4],h[0][5]]
    
    for i in y:
        max_value = book_pivotub.loc[i].max()  
        max_indices = book_pivotub.loc[i][book_pivotub.loc[i] == max_value].index.tolist()  
        max_index = random.choice(max_indices)  
        print(max_index)

In [60]:

book_recommendations_UserBased_CF(278188)

The Street Lawyer
The Hobbit : The Enchanting Prelude to The Lord of the Rings
Digital Fortress : A Thriller
Wanderlust
The Burden of Proof


Hybrid Recommender System

In [61]:
def hybrid_recommender(book_already_read, user_id, weight_for_history):
    import random
    
    def book_recommendations_UserBased_CF(user_id):
            try:
                serial_no=book_pivotub.index.get_loc(user_id)
                
            except KeyError:
                print("Sorry! UserID",user_id,"not Valid.")
                
            distance,suggestions=modelub.kneighbors(book_pivotub.loc[user_id].values.reshape(1,-1), n_neighbors=6)
            h=[]
            for i in suggestions:
                h.append(book_pivotub.index[i])
            y=[h[0][1],h[0][2],h[0][3],h[0][4],h[0][5]]
            z=[]
            for i in y:
                max_value = book_pivotub.loc[i].max()  
                max_indices = book_pivotub.loc[i][book_pivotub.loc[i] == max_value].index.tolist()  
                max_index = random.choice(max_indices)
                z.append(max_index)
            z=np.array(z)
            z=z.flatten()
            return z
    def recommend_book_itemBased_CF(book_already_read):
            book_id=np.where(book_pivotib.index==book_already_read)[0][0]
            distance,suggestions=modelib.kneighbors(book_pivotib.iloc[book_id,:].values.reshape(1,-1), n_neighbors=6)
            x=np.array(suggestions)
            x=x.flatten()
            y=[]
            for i in x:
                y.append(book_pivotib.index[i])
            y=np.array(y)
            y=y.flatten()
            return y
    z=book_recommendations_UserBased_CF(user_id)
    y=recommend_book_itemBased_CF(book_already_read)
    k=int(np.floor(weight_for_history*len(y)))
    m=random.sample(y.tolist(),k)
    for i in range(len(z)-k):
        m.append(z[i])
    print("Hybrid Recommendations\n")
    for i in m:
        print(i)

In [62]:

hybrid_recommender('How Stella Got Her Groove Back',269728,0.4)

Hybrid Recommendations

Journey
While My Pretty One Sleeps
The Blue Nowhere : A Novel
The Kitchen God's Wife
The Handmaid's Tale